<a href="https://colab.research.google.com/github/MIRYALASAITEJA/23CSBTB30/blob/main/1stLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,5,6,9])
print(np.sort(arr))

[1 5 6 9]


In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a+b)
print(c)

[ 6  8 10]


In [6]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a-b)
print(c)

[-4 -4 -4]


In [7]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a*b)
print(c)

[ 5 12 21]


In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a/b)
print(c)

[0.2        0.33333333 0.42857143]
